version: "3.9"

services:

  db:
    image: postgres:15
    container_name: autograder_db
    restart: always
    env_file:
      - .env-docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: autograder_app
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env-docker
    depends_on:
      - db
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000" 
    volumes:
      - ./:/app



volumes:
  pgdata:
